apiVersion: v1
kind: Pod
metadata:
  name: java-app
spec:
  containers:
  - name: java-app 
    image: sanmodi/jenkins_upload_pipeline:latest
    command: ['sh', '-c', 'echo The app is running! && sleep 10000']
